### ISSUE TITLE
PSS not calculated for trainer ride with no distance

### ISSUE THREAD

**Issue by cmagnuson** [thomaschampagne/elevate#735]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.8.1 stable
  * Chrome/Opera/Chromium version: 71.0.3578.98 (Official Build) (64-bit)
  * OS version: OSX 10.12.6
  
### Step 3: Describe the problem:
For all of my trainer rides where I've disabled the GPS, PSS isn't calculated.  Strava calculates the weighted average power as expected, but Elevate does not (divide by 0?), and has a note to configure FTP settings to get "Power Stress Score".  I see PSS also isn't listed for trainer rides in the Fitness Trend.  PSS is calculated as expected on outdoor rides with GPS enabled.

#### Steps to reproduce:

  1. Upload ride with GPS disabled, so distance traveled is 0 miles.

#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
google.loader.f @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:23
2065611390/power_data:1 Failed to load resource: the server responded with a status of 401 ()

VM330:4 GET https://www.strava.com/activities/2065611390/power_data 401
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  PSS calculated

#### Media attachement:

>You can upload/attach any images to this ticket.

<img width="414" alt="screen shot 2019-01-08 at 7 16 42 pm" src="https://user-images.githubusercontent.com/1679980/50869728-e32fa880-137a-11e9-9039-390d3412596b.png">

#### Providing your Elevate synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by dexe3** [comment]
Same behaviour on win10 and latest chrome version.

**Comment by eferber** [comment]
same problem, files generated using indoor mode on wahoo elemnt

**Comment by thomaschampagne** [comment]
Can you provide me a fit file to debug? Also activity ids?

**Comment by harblhat** [comment]
> Can you provide me a fit file to debug? Also activity ids?

Sent via email

**Comment by viniga** [comment]
Also experienced this issue. 0k indoor ride on turbo with power recorded by Garmin 520.

**Comment by thomaschampagne** [comment]
@eferber Could you temporally make public your 2 activities:

https://www.strava.com/activities/2085128229
https://www.strava.com/activities/2082879533

?

Thanks :)

**Comment by thomaschampagne** [comment]
Ok i have the solution 😄 !!

You have to make sure that these activities are flagged as **Indoor Cycling** in strava (see images). Otherwise power stream is not accessible, and PSS is not calculated. After setting the flag manually on your activities in strava, just perform a **clear & re-sync activities** in elevate app. Problem should be fixed.

Also you may have an option on your GPS to set your training session as "Indoor". So when uploading to strava, the flag  **Indoor Cycling** is automatically set. I know i can do that on my Garmin Edge profiles. 

If a Wahoo Element GPS and according to the instructions: https://eu.wahoofitness.com/instructions/elemnt-bolt#profile. You may go to **SETTINGS MENU** > **Location** > _Set to Indoor/Outdoor. (Will turn off GPS and elevation when indoors.)_

@cmagnuson If problem is fixed you can close this ticket.

![image](https://user-images.githubusercontent.com/151973/52002844-4d8fc080-24c3-11e9-8725-9284314ad082.png)

![image](https://user-images.githubusercontent.com/151973/52003022-b5dea200-24c3-11e9-871d-95207eeb2a75.png)

![image](https://user-images.githubusercontent.com/151973/52003065-d73f8e00-24c3-11e9-8cea-833344481f28.png)

**Comment by harblhat** [comment]
Hello,

Trainerroad automatically flags all of its activities as indoor cycling, and I have confirmed that the tags are applied as you said. 

![image](https://user-images.githubusercontent.com/46872532/52004179-882e3480-2494-11e9-9d29-684806735d1d.png)

This doesn't solve the issue, as none of these rides have a PSS calculated. 

![image](https://user-images.githubusercontent.com/46872532/52004297-c6c3ef00-2494-11e9-8298-913df309fdbe.png)

**Comment by thomaschampagne** [comment]
@harblhat Can you provide me activity link of this "Ramp Test" (public accessible)?

**Comment by harblhat** [comment]
> @harblhat Can you provide me activity link of this "Ramp Test" (public accessible)?

Here you go: https://www.strava.com/activities/2112275292

**Comment by cmagnuson** [comment]
I'm also still seeing it - the activities were already flagged as "Indoor Cycling", here is an example:
https://www.strava.com/activities/2112358474

**Comment by cmagnuson** [comment]
Using the same GPS (Edge 500) but a different power meter last year I did not experience the issue:
https://www.strava.com/activities/1390360526

The only obvious difference I see in the data they provide is a speed was generated from last year's power meter (trainer) but isn't provided by my current power meter.

**Comment by viniga** [comment]
Indoor trainer tags set correctly for me. I also only note this when no speed data is provided.

**Comment by thomaschampagne** [comment]
I found the problem. The CI will generate a test build available in ~15 minutes

I will give you the link in a new comment

**Comment by thomaschampagne** [comment]
Here's the test build that fix this bug: https://bitbucket.org/thomaschampagne/elevate-ci-builds/downloads/v6.9.0_stable_2019-01-30-20-01.develop.9bed3a9f.zip

@cmagnuson You can reopen the bug if not fixed

**Comment by cmagnuson** [comment]
Fix is working as expected, thanks!

**Comment by harblhat** [comment]
Working for me as well. Thank you!
